name: Keep Streamlit App Awake

on:
  schedule:
    # This runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # This allows you to run it manually for testing

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run ping script
        run: python keep_awake.py
